config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.set :session_secret, Rails.application.secrets.secret_key_base

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    secrets = Rails.application.secrets

    secure_compare_username = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_username, username)
    secure_compare_password = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_password, password)

    secure_compare_username && secure_compare_password
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[show edit update] do
    controller 'users' do
      post 'validate'
      get 'travels', action: 'index_travels'
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      get 'followings', action: 'index_followings'
      get 'followers', action: 'index_followers'
      post 'followers', action: 'create_followers'
      delete 'followers', action: 'destroy_followers'
      put 'image', action: 'update_image'
      patch 'image', action: 'update_image'
      get 'posts', action: 'index_posts'

      collection do
        get 'search'
      end
    end
  end

  resources :travels, only: %i[show create destroy new] do
    controller 'travels' do
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      post 'favorites', action: 'create_favorites'
      delete 'favorites', action: 'destroy_favorites'
      get 'comments', action: 'index_comments'
      post 'comments', action: 'create_comments'

      collection do
        get 'search'
      end
    end
  end

  resources :comments, only: %i[show destroy] do
    get 'search', on: :collection
  end

  resources :notifications, only: %i[index] do
    post 'read', on: :collection
  end

  get '/home', to: 'home#home'
  get '/posts', to: 'home#posts'

  root 'home#root'
end

app/models/concerns/searchable/travel.rb
# frozen_string_literal: true

module Searchable
  module Travel
    extend ActiveSupport::Concern
    include Searchable::Search

    included do
      scope :title_like, ->(query) { where('title ILIKE ?', "%#{query}%") }
      scope :description_like, ->(query) { where('description ILIKE ?', "%#{query}%") }
      scope :search_token, ->(query) { title_like(query).or(description_like(query)) }
    end
  end
end

app/models/travel.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: travels
#
#  id                   :uuid             not null, primary key
#  title                :string           not null
#  description          :text             default(""), not null
#  image_public_url     :text
#  thumbnail_public_url :text
#  publicx              :boolean          default(TRUE), not null
#  user_id              :uuid             not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id) ON DELETE => cascade
#

class Travel < ApplicationRecord
  include Imageable
  include Searchable::Travel

  belongs_to :user

  has_one :event, as: :resource, dependent: :destroy

  has_many :authorizations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :places, inverse_of: :travel, dependent: :destroy

  has_many :authorizations_users, through: :authorizations, source: :user
  has_many :comments_users, through: :comments, source: :user
  has_many :favorites_users, through: :favorites, source: :user

  validates :title, length: { in: 2..30 }
  validates :description, length: { maximum: 1000 }
  validates :places, length: { in: 1..25 }

  after_create_commit :create_event!
  after_create_commit :download_image!

  accepts_nested_attributes_for :places

  scope :privatex, -> { where(publicx: false) }
  scope :publicx, -> { where(publicx: true) }

  ##
  # Devuelve si el viaje puede ser accedido por un determinado usuario.
  #
  def readable?(user)
    publicx || user == self.user || authorizations_users.include?(user) || user&.admin?
  end

  ##
  # Devuelve si el viaje puede ser gestionado por un determinado usuario.
  #
  def manageable?(user)
    user == self.user || user&.admin?
  end

  ##
  # Autoriza a un usuario a acceder al viaje.
  #
  def authorize!(user)
    authorizations.find_or_create_by!(user: user)
  end

  ##
  # Autoriza a una lista de usuarios a acceder al viaje.
  #
  def authorize_all!(users)
    Array(users).map { |user| authorize!(user) }
  end

  ##
  # Devuelve la URL de la imagen de previsualización de un viaje dado.
  #
  def image_url
    ApolloGoogleMaps.image_url(self)
  end

  private

  ##
  # Crea el evento de la creación del viaje.
  #
  def create_event!
    # EventCreationJob.perform_later(
    #   source: user,
    #   resource: self
    # )
  end

  ##
  # Descarga la imagen de previsualización y ajusta la ruta de destino de la imagen.
  #
  def download_image!
    EventCreationJob.new.perform(
      source: user,
      resource: self
    )

    TravelImageCreationJob.new.perform(self)
  end
end

app/controllers/travels_controller.rb
# frozen_string_literal: true

class TravelsController < ApplicationController
  before_action :authenticate_user!, only: %i[
    create
    destroy
    create_comments
    create_favorites
    destroy_favorites
    new
  ]

  before_action :set_travel, except: %i[
    create
    search
    new
  ]

  before_action :only_manager_users, only: %i[destroy]

  def new
    render 'travels/new'
  end

  def show
    respond_to do |format|
      format.html { render 'travels/show.html' }
      format.json { render :show }
    end
  end

  def create
    @travel = nil

    ActiveRecord::Base.transaction do
      @travel = Travel.create!(create_params)
      @travel.authorize_all!(authorizations_users) unless @travel.publicx?
    end

    respond_to do |format|
      format.html { redirect_to travel_path(@travel.format_id) }
      format.json { render 'travels/show.json', status: :created }
    end
  end

  def destroy
    @travel.destroy!

    respond_to do |format|
      format.html do
        flash[:icon] = 'fas fa-fw fa-map-marker-alt'
        flash[:success] = 'El viaje fue eliminado correctamente.'
        redirect_to home_path
      end

      format.json do
        head :no_content
      end
    end
  end

  def search
    @travels = Travel.search(search_params).order(created_at: :desc)

    render :index
  end

  def index_authorizations
    @authorizations = @travel.authorizations

    render 'authorizations/index'
  end

  def index_comments
    @comments = @travel.comments

    render 'comments/index'
  end

  def create_comments
    @comment = current_user.comment!(@travel, comment_params)

    respond_to do |format|
      format.html { redirect_to travel_path(@comment.travel_id) }
      format.json { render 'comments/show', status: :created }
    end
  end

  def index_favorites
    @favorites = @travel.favorites

    render 'favorites/index'
  end

  def create_favorites
    @favorite = current_user.favorite!(@travel)

    respond_to do |format|
      format.html do
        redirect_back fallback_location: travel_path(@travel.format_id)
      end

      format.json do
        render '/favorites/show'
      end
    end
  end

  def destroy_favorites
    current_user.unfavorite!(@travel)

    respond_to do |format|
      format.html do
        redirect_back fallback_location: travel_path(@travel.format_id)
      end

      format.json do
        head :no_content
      end
    end
  end

  private

  def set_travel
    travel_id = params[:id] || params[:travel_id]

    @travel = Travel.find(travel_id)

    unless @travel.readable?(current_user)
      raise ActiveRecord::RecordNotFound.new(nil, Travel, :id, travel_id)
    end

    @travel
  end

  def create_params
    places = params.fetch(:places).map do |plc|
      longitude = plc.fetch(:longitude)
      latitude = plc.fetch(:latitude)

      {
        title: plc.fetch(:title),
        description: plc.fetch(:description),
        coordinates: "POINT(#{longitude} #{latitude})"
      }
    end

    {
      title: params.fetch(:title),
      description: params[:description],
      publicx: params.fetch(:public, true),
      places_attributes: places,
      user: current_user
    }
  end

  def comment_params
    params.fetch(:content)
  end

  def search_params
    params.fetch(:query, '')
  end

  def authorizations_users
    User.where(id: params.fetch(:authorizations, []))
  end

  def only_manager_users
    return if @travel.manageable?(current_user)

    raise Apollo::UserNotAuthorized.new(@travel, params[:action])
  end
end

app/views/travels/list.html.erb
<div class="row">
  <div class="col-3">
    <%= render partial: 'users/partials/user_lateral',
               locals: {
                 user: @user
               }
    %>
  </div>

  <div class="col-9" align="center">
    <% @travels.each do |travel| %>
      <%= render partial: "travels/partials/travel_min",
                 locals: {
                   travel: travel,
                   user: @user
                 }
      %>
    <% end %>
  </div>
</div>

app/views/travels/new.html.erb
<div class="row p-4">

    <div class="col-4 w-100">
      <div class="row w-100">
        <div class="alert alert-primary w-100 d-flex justify-content-center">
          <strong>Nueva Ruta de Viaje</strong>
        </div>
        <%= form_with url: travels_url, id: "rvform", html: { autocomplete: "off" }, class:"w-100 border rounded shadow p-3 mb-5 bg-white" do |form| %>
          <%= form.label :titulo %>
          <%= form.text_field :title, class: "form-control mb-2", required: true, minlength: 2, maxlength: 30 %>

          <%= form.label "Descripción" %>
          <%= form.text_area :description, class: "form-control mb-2", maxlength: 1000 %>

          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Visibilidad</label>
            <div class="col-sm-10">
              <select class="form-control" id="privacy" name="public">
                <option value="true">Publica</option>
                <option value="false">Privada</option>
              </select>
            </div>
          </div>

          <div class="form-group row d-none" id="select_users">
            <label class="col-sm-2 col-form-label">Usuarios</label>
            <div class="col-sm-10 w-100">
              <%= select("private", "users", current_user.followers_users.map {|u| [ "@"+u.username, u.format_id ] }, {include_blank: ""}, style:"width:100% !important", name:"authorizations", multiple:"multiple") %>
            </div>
          </div>

          <label >Lugares</label>
          <div id="places-list"></div>

          <%= form.submit "Enviar", id: "submitBtn", class: "btn btn-primary rounded" %>
        <% end %>
      </div>
    </div>

    <div class="col-8" style="height:75vh;">
      <input id="pac-input" class="form-control controls" type="text" placeholder="Buscar">
      <div id="map"></div>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.secrets.apollo_google_maps_key %>&libraries=places&language=es&region=AR"></script>
        <script>
          var line = null;
          var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 8,
            zoomControl: true,
            mapTypeControl: false,
            scaleControl: false,
            streetViewControl: false,
            rotateControl: false,
            fullscreenControl: false
          });
        </script>
    </div>

</div>


<script>
//Instanciar el select de los usuarios que podran ver la rv privada
$("#privacy").on("change", function(){
  var val = $("#privacy").val();
  if (val == "false"){
    $("#select_users").removeClass("d-none");
    $("#private_users").select2({
      width: 'element',
      minimumResultsForSearch: Infinity
    });
  } else {
    $("#select_users").addClass("d-none");
  }
})


// tamanio maximo de titulo de place 30 caracteres
// tamanio maximo de description de place fijarse en modelo
var markers = []
const mkMarker = (map, lat, lang, title) => {
  return new google.maps.Marker({
    position: {lat: lat, lng: lang},
    map: map,
    title: title,
    label: String.fromCharCode(65 + markers.length)
  })
}

map.addListener('click', e => {
  const m = mkMarker(map, e.latLng.lat(), e.latLng.lng(), "Marker")
  markers.push(m)
  draw_line(map, markers);
  add_place(e.latLng.lat(), e.latLng.lng());
});

map.addListener('mousedown', e => {
  if (e.ua.buttons === 2) {
    removedMarker = markers.pop();
    removedMarker.setMap(null);
    draw_line(map, markers);
    remove_place();
  }
});

const add_place = (lat, lng) => {
  var newPlaceCoords = newPlaceForm(lat, lng);
  var newItem = document.createTextNode(newPlaceCoords);
  $("#places-list").append(newPlaceCoords)
}


const newPlaceForm = (lat, lng) => {
  var node = `
  <div id="place-${markers.length}" class="place-item border rounded p-2 mb-2">
    <input type="hidden" name="places[][latitude]" value="${lat}" />
    <input type="hidden" name="places[][longitude]" value="${lng}" />
    <div class="alert alert-info w-100 d-flex justify-content-center"> <strong>${String.fromCharCode(64 + markers.length)}</strong> </div>
    <input id="place-item-title" name="places[][title]" class="form-control mb-2" placeholder="Titulo" type="text" maxlength=65 required>
    <textarea id="place-item-desc" name="places[][description]" class="form-control mb-2" placeholder="Descripción" type="textarea" maxlength=150 />
  </div>
  `
  return node;
}

const remove_place = () => {
  $('div:last-child', $('#places-list')).remove();
}

const draw_line = (map, markers) => {
  line ? line.setMap(null) : null;
  line = new google.maps.Polyline({
    path: markers.map(marker => marker.position),
    geodesic: true,
    strokeColor: '#FF0000',
    strokeOpacity: 1.0,
    strokeWeight: 2
  });

  line.setMap(map);
}

const initAutocomplete = (map) => {
    var input = document.getElementById('pac-input');
    var searchBox = new google.maps.places.SearchBox(input);

    map.controls[google.maps.ControlPosition.TOP_RIGHT].push(input);
    searchBox.addListener('places_changed', function() {
      var places = searchBox.getPlaces();

      if (places.length == 0) {
        return;
      }


    // Bias the SearchBox results towards current map's viewport.
    map.addListener('bounds_changed', () => searchBox.setBounds(map.getBounds()))

    // For each place, get the icon, name and location.
    var bounds = new google.maps.LatLngBounds();
    places.forEach(function(place) {
      if (!place.geometry) {
        console.log("Returned place contains no geometry");
        return;
      }
      var icon = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };

      if (place.geometry.viewport) {
        bounds.union(place.geometry.viewport);
      } else {
        bounds.extend(place.geometry.location);
      }
    })
    map.fitBounds(bounds)
});
}


initAutocomplete(map)

</script>

app/views/travels/show.html.erb
<div class="row">
    <div class="col-md-8 p-2">
        <div id="travel-wrapper" class="position-relative">
            <% if @travel.manageable?(current_user) %>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-link btn-delete position-absolute no-decoration" data-toggle="modal" data-target="#deleteTravel" title="Eliminar viaje">
                  <i class="fas fa-trash-alt"></i>
                </button>
            <% end %>

            <div id="rv_map" style="height:75vh;"></div>
        </div>

        <h3 class="my-2">
            <%= @travel.title %>
            <% unless @travel.publicx? %>
                <i class="fas fa-lock"></i>
            <% end %>
        </h3>
        <p>
            Por <%= link_to user_path(@travel.user_id) do %>
                @<%= @travel.user.username %>
            <% end %>

            <span class="date"> hace <%= time_ago_in_words @travel.created_at %></span>
        </p>

        <p><%= @travel.description %></p>

      <div class="d-flex flex-row-reverse travel-buttons">
        <% comment_class = 'active' if current_user&.comment?(@travel) %>

        <button type="button" class="btn btn-comment btn-link no-decoration <%= comment_class %>">
          <i class="far fa-fw fa-comment"></i>
          <i class="fas fa-fw fa-comment"></i>
          <%= @travel.comments.count %>
        </button>

        <% if current_user.favorite?(@travel) %>
          <%= button_to travel_favorites_path(travel_id: @travel.format_id), method: :delete, class: 'btn btn-favorite btn-link no-decoration active' do %>
              <i class="far fa-fw fa-star"></i>
              <i class="fas fa-fw fa-star"></i>
              <%= @travel.favorites.count %>
          <% end %>
        <% else %>
          <%= button_to travel_favorites_path(travel_id: @travel.format_id), class: "btn btn-favorite btn-link no-decoration" do %>
              <i class="far fa-fw fa-star"></i>
              <i class="fas fa-fw fa-star"></i>
              <%= @travel.favorites.count %>
          <% end %>
        <% end %>
      </div>

        <% @travel.comments.each do |comment| %>
            <%= render partial: "travels/partials/comment",
                    locals: {
                        comment:comment
                    }
            %>
        <% end %>

        <%= form_for :comment, url: travel_comments_path(travel_id: @travel.format_id) do |f|%>
            <div class="form-group">
                <textarea class="form-control" name="content" rows="3" maxlength="300" placeholder="Agregar comentario...", required></textarea>
            </div>
            <%= f.submit "Comentar", class:"btn btn-secondary" %>
        <% end %>

    </div>

    <div class="col-md-4 p-2">
        <% @travel.places.each_with_index do |place, index| %>
            <%= render partial: "travels/partials/place",
                    locals: {
                        place:place,
                        index:index
                    }
            %>
        <% end %>
    </div>

</div>

<% if @travel.manageable?(current_user) %>
    <!-- Modal -->
    <div class="modal fade" id="deleteTravel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Eliminar viaje</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ¿Estás seguro de querer eliminar este viaje? Esta acción no se puede deshacer.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <%= button_to 'Eliminar', travel_path(@travel.format_id), method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.secrets.apollo_google_maps_key %>&libraries=places&language=es&region=AR"></script>
<script>
    var places = <%= @travel.places.map do |place|
                     place.slice(:lat, :lng)
                 end.to_json.html_safe %>;
    var line = null;
    var map = new google.maps.Map(document.getElementById('rv_map'), {
    center: {lat: places[0].lat, lng: places[0].lng},
    zoom: 8,
    zoomControl: true,
    mapTypeControl: false,
    scaleControl: false,
    streetViewControl: false,
    rotateControl: false,
    fullscreenControl: false
    });

    const put_places = () =>
        places.map((place, index) => {
            return new google.maps.Marker({
                position: {lat: place.lat, lng: place.lng},
                map: map,
                label: String.fromCharCode(65 + index)
            })
        });



    const good_markers = put_places();

    const draw_line = (markers) => {
        line ? line.setMap(null) : null;
        line = new google.maps.Polyline({
            path: markers.map(marker => marker.position),
            geodesic: true,
            strokeColor: '#FF0000',
            strokeOpacity: 1.0,
            strokeWeight: 2
        });

        line.setMap(map);
    }

    draw_line(good_markers)
</script>