config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.set :session_secret, Rails.application.secrets.secret_key_base

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    secrets = Rails.application.secrets

    secure_compare_username = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_username, username)
    secure_compare_password = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_password, password)

    secure_compare_username && secure_compare_password
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[show edit update] do
    controller 'users' do
      post 'validate'
      get 'travels', action: 'index_travels'
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      get 'followings', action: 'index_followings'
      get 'followers', action: 'index_followers'
      post 'followers', action: 'create_followers'
      delete 'followers', action: 'destroy_followers'
      put 'image', action: 'update_image'
      patch 'image', action: 'update_image'
      get 'posts', action: 'index_posts'

      collection do
        get 'search'
      end
    end
  end

  resources :travels, only: %i[show create destroy new] do
    controller 'travels' do
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      post 'favorites', action: 'create_favorites'
      delete 'favorites', action: 'destroy_favorites'
      get 'comments', action: 'index_comments'
      post 'comments', action: 'create_comments'

      collection do
        get 'search'
      end
    end
  end

  resources :comments, only: %i[show destroy] do
    get 'search', on: :collection
  end

  resources :notifications, only: %i[index] do
    post 'read', on: :collection
  end

  get '/home', to: 'home#home'
  get '/posts', to: 'home#posts'

  root 'home#root'
end

app/views/posts/partials/_comment_post.html.erb
<% resource = post.resource %>
<% resource_user = resource.user %>
<% resource_travel = resource.travel %>

<div class="row mb-4">
  <div class="col-2">
    <%= image_tag resource_user.image_url, class: 'img-thumbnail' %>
  </div>

  <div class="col-10">
    <div class="mb-2">
      <%= link_to user_path(resource_user.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource_user.username %>
        </strong>
      <% end %>

      comentó

      <%= link_to travel_path(resource_travel.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource_travel.title %>
        </strong>
      <% end %>

      <span class="date"> hace <%= time_ago_in_words resource.created_at %></span>
    </div>

    <%= render partial: 'travels/partials/travel_min',
              locals: {
                user: user,
                travel: resource_travel
              }
    %>
  </div>
</div>

app/views/posts/partials/_favorite_post.html.erb
<% resource = post.resource %>
<% resource_user = resource.user %>
<% resource_travel = resource.travel %>

<div class="row mb-4">
  <div class="col-2">
    <%= image_tag resource_user.image_url, class: 'img-thumbnail' %>
  </div>

  <div class="col-10">
    <div class="mb-2">
      <%= link_to user_path(resource_user.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource_user.username %>
        </strong>
      <% end %>

      marcó como favorito

      <%= link_to travel_path(resource_travel.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource_travel.title %>
        </strong>
      <% end %>

      <span class="date"> hace <%= time_ago_in_words resource.created_at %></span>
    </div>

    <%= render partial: 'travels/partials/travel_min',
              locals: {
                user: user,
                travel: resource_travel
              }
    %>
  </div>
</div>

app/views/posts/partials/_following_post.html.erb
<% resource = post.resource %>

<div class="row mb-4">
  <div class="col-2">
    <%= image_tag resource.follower.image_url, class: 'img-thumbnail' %>
  </div>

  <div class="col-10">
    <div class="mb-2">
      <%= link_to user_path(resource.follower.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource.follower.username %>
        </strong>
      <% end %>

      empezó a seguir a

      <%= link_to user_path(resource.following.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource.following.username %>
        </strong>
      <% end %>

      <span class="date"> hace <%= time_ago_in_words resource.created_at %></span>
    </div>

    <%= render partial: 'followings/partials/follower',
              locals: {
                follower: resource.following
              }
    %>
  </div>
</div>

app/views/posts/partials/_travel_post.html.erb
<% resource = post.resource %>
<% resource_user = resource.user %>

<div class="row mb-4">
  <div class="col-2">
    <%= image_tag resource_user.image_url, class: 'img-thumbnail' %>
  </div>

  <div class="col-10">
    <div class="mb-2">
      <%= link_to user_path(resource_user.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource_user.username %>
        </strong>
      <% end %>

      creó

      <%= link_to travel_path(resource.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource.title %>
        </strong>
      <% end %>

      <span class="date"> hace <%= time_ago_in_words resource.created_at %></span>
    </div>

    <%= render partial: 'travels/partials/travel_min',
              locals: {
                user: user,
                travel: resource
              }
    %>
  </div>
</div>

app/views/posts/partials/_user_post.html.erb
<% resource = post.resource %>

<div class="row mb-4">
  <div class="col-2">
    <%= image_tag resource.image_url, class: 'img-thumbnail' %>
  </div>

  <div class="col-10">
    <div class="mb-2">
      <%= link_to user_path(resource.format_id), class: 'no-decoration' do %>
        <strong class="text-body">
          <%= resource.username %>
        </strong>
      <% end %>

      se unió a Apollo

      <span class="date"> hace <%= time_ago_in_words resource.created_at %></span>
    </div>

    <%= render partial: 'followings/partials/follower',
              locals: {
                follower: resource
              }
    %>
  </div>
</div>