config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.set :session_secret, Rails.application.secrets.secret_key_base

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    secrets = Rails.application.secrets

    secure_compare_username = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_username, username)
    secure_compare_password = ActiveSupport::SecurityUtils.secure_compare(secrets.sidekiq_password, password)

    secure_compare_username && secure_compare_password
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[show edit update] do
    controller 'users' do
      post 'validate'
      get 'travels', action: 'index_travels'
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      get 'followings', action: 'index_followings'
      get 'followers', action: 'index_followers'
      post 'followers', action: 'create_followers'
      delete 'followers', action: 'destroy_followers'
      put 'image', action: 'update_image'
      patch 'image', action: 'update_image'
      get 'posts', action: 'index_posts'

      collection do
        get 'search'
      end
    end
  end

  resources :travels, only: %i[show create destroy new] do
    controller 'travels' do
      get 'authorizations', action: 'index_authorizations'
      get 'favorites', action: 'index_favorites'
      post 'favorites', action: 'create_favorites'
      delete 'favorites', action: 'destroy_favorites'
      get 'comments', action: 'index_comments'
      post 'comments', action: 'create_comments'

      collection do
        get 'search'
      end
    end
  end

  resources :comments, only: %i[show destroy] do
    get 'search', on: :collection
  end

  resources :notifications, only: %i[index] do
    post 'read', on: :collection
  end

  get '/home', to: 'home#home'
  get '/posts', to: 'home#posts'

  root 'home#root'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apollo</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <%= javascript_include_tag 'moment-with-locales.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'new_travel', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <script type="text/javascript">
    moment.locale('es');

    $(function() {
      var $displays = $('.moment-display');

      $displays.each(e => {
        let $e = $($displays[e])
        let time = moment($e.data('time'));
        let text = time.fromNow();
        text = text.charAt(0).toUpperCase() + text.slice(1);
        $e.text(text);
      });
    })
  </script>

  <body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-light bg-primary mb-2">
        <% if current_user %>
          <%= link_to home_path, class: "navbar-brand text-white", id: "logo" do %>
            <%= image_tag 'logo.png', style: "height: 30px;", class: 'mr-1' %>
            <strong>APOLLO</strong>
          <% end %>

          <div class="collapse navbar-collapse">
            <% if current_user.confirmed? %>
              <span class="badge text-white" style="font-size: 115%;"><i class="fas fa-search mr-1"></i></span>

              <%= select("search", "user_id", User.all.collect {|u| [ "@"+u.username, u.format_id ] }, {include_blank: 'Search...'}, class:"w-100") %>
            <% end %>

            <ul class="navbar-nav w-100  d-flex flex-row-reverse">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= image_tag current_user.thumbnail_public_url, style: "height: 30px;", class: 'mr-1' %>
                    <strong><%= current_user.name %></strong>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <%= link_to "Editar usuario", edit_user_path(current_user.format_id), class:"dropdown-item text-dark" %>
                    <%= link_to "Cerrar sesion", signout_path, id: "sign_out", class:"dropdown-item text-dark" %>
                  </div>
              </li>

              <% if current_user.confirmed? %>
                  <%= link_to new_travel_path, class:"btn btn-success rounded" do %>
                    <i class="fas fa-plus mr-1"></i>Ruta de Viaje
                  <% end %>
              <% end %>
            </ul>
          </div>
        <% else %>
        <a href="/" class="navbar-brand">

              <div class="titulo text-white">APOLLO</div>
          </a>
      </a>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="navbar-nav w-100 d-flex justify-content-end">
          <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li>
            <a class="nav-item mr-2 page-scroll" href="#about">Acerca de</a>
          </li>
          <li>
            <a class="nav-item mr-2 page-scroll" href="#nosotros">Nosotros</a>
          </li>
          <li>
            <a class="nav-item mr-2 page-scroll" href="#contact">Contacto</a>
          </li>
        </ul>
      </div>
      <% end %>
    </nav>

    <div class="container-fluid mt-4">
      <%= yield %>
    </div>

    <script>
      $(document).ready(function() {
        $("#search_user_id").select2();
      });

      $("#search_user_id").on("change", function(){
        var id = $(this).val();
        window.location = "/users/" + id;
      })
    </script>
  </body>
</html>